### ISSUE TITLE
Develop the Database

### ISSUE THREAD

**Issue by mugdha-gupta** [mugdha-gupta/ShopAuth#10]
- [ ] Database SQL code (Sprint Boot?)

- [ ] Build API

- [ ] Populate with dummy data

- [ ] Brief the team

**Comment by Sm1tShah** [comment]
Chris and Daniel worked on the code and they had me take a quick look on it today.

We didn't comment the code for the table creation code because some of the numbers might change as the project develops but we do plan on going back and adding comments where necessary.

Also, we will work on SQL queries that calculate non-trivial statistics as a stretch goal.
